#! /bin/bash
#i2cset -y 2 0x00 0x00 0x00
#this script reads from 2 tmp101 sensors and reports
#the output in farenheit.
#parameters
tmpaddress1=$1 #input as a hex value i.e: 0x48 or 0x40
tmpaddress2=$2 #input as a hex
#
rawtemp1=$(i2cget -y 2 tmpaddress1)
rawtemp2=$(i2cget -y 2 tmpaddress2)
rawtemp1dec=$((rawtemp1)) 
rawtemp2dec=$((rawtemp2)) 
temp1F=$(echo $rawtemp1dec*1.8 | bc)
temp1F=$(echo $temp1F + 32 | bc)
temp2F=$(echo $rawtemp2dec*1.8 | bc)
temp2F=$(echo $temp2F + 32 | bc)
#echo $rawtemp1
#echo $rawtemp2
echo $temp1F
echo $temp2F
